### ISSUE TITLE
License mismatch in 1.021

### ISSUE THREAD

**Issue by ppisar** [briandfoy/io-interactive#2]
The recently added LICENSE file states:

~~~~
The IO::Interactive module is licensed under the same terms as perl
itself, under the Artistic License 2.0.
~~~~

This is nonsense as perl is under (GPL+ or Artistic) license [http://dev.perl.org/licenses/]. You have mistaken Perl 5 and Perl 6 probably. The second one uses Artistic 2.0.

Could please clarify what license does apply to IO-Interactive-1.021?

**Comment by briandfoy** [comment]
As it says, Artistic 2.0.

**Comment by ppisar** [comment]
On Thu, Jan 28, 2016 at 03:07:14PM -0800, brian d foy wrote:
> As it says, Artistic 2.0. 
> 
Thank you for the clarification. Could you then please remove the "the same
terms as perl itsef" words from LICENSE and lib/IO/Interactive.pm files? It's
higly confusing.

**Comment by briandfoy** [comment]
Is this in any way preventing you from doing something you'd like to do?

**Comment by ppisar** [comment]
On Fri, Jan 29, 2016 at 08:49:30AM -0800, brian d foy wrote:
> Is this in any way preventing you from doing something you'd like to do?
> 
No, it doesn't. It just raises eyebrows of those who fills the license data
into software package metadata and who see that global statement "this is
Artistic 2.0" does not match the "same as Perl" statement in the module file
and thus they have to mark such package as ((Artistic 2.0) and (GPLv+ or
Artistic)) what probably does not agree with you intention but what reality
is.
