### ISSUE TITLE
Useless dependency on version module

### ISSUE THREAD

**Issue by ppisar** [briandfoy/io-interactive#3]
Makefile.PL as well as META files declares dependency on version module that is nowhere used in the IO-Interactive-1.021. I think it can be removed from the Makefile.PL.

**Comment by briandfoy** [comment]
As I recall, there was something implicit in earlier versions of version that caused problems since $VERSION is a v-string.

**Comment by briandfoy** [comment]
Ah, but I took out the v-string!

**Comment by briandfoy** [comment]
Fixed in 60b3097e8752711fdd6454b16674fe02a3e7a923. Pull requests are good too, and take about as much time as filing an issue :)
