### ISSUE TITLE
is_interactive always returns true for a Windows Scheduled Task

### ISSUE THREAD

**Issue by robrwo** [briandfoy/io-interactive#6]
I have run into the following issue in Windows. I think it should be documented:

When using IO::Interactive in the Windows environment, then `is_interactive` will always return true when the program is run as a Scheduled Task, even when it is run as the "SYSTEM" user.

**Comment by briandfoy** [comment]
If someone with Windows experience can either fix the feature or verify the problem, then send a pull request, I'll merge it.

**Comment by briandfoy** [comment]
I've made a note in 4fcacba9741da1a4127edafda3e6f71aaaaa6a84, but I'd like to see what we can do to make this work as people expect.

**Comment by briandfoy** [comment]
I tried again to solve this again, but I've given up now that I've read Raymond Chen's [How can I detect that my program was run from Task Scheduler, or my custom shortcut, or a service, or whatever](https://devblogs.microsoft.com/oldnewthing/20140228-00/?p=1633). If he doesn't know how it can be done, it probably can't be done, even if I disagree with him on the wisdom of doing it.
