### ISSUE TITLE
Please document why I should use IO::Interactive instead of -t

### ISSUE THREAD

**Issue by josch** [briandfoy/io-interactive#9]
Hi,

I came here, because I ran into this:

https://metacpan.org/pod/Perl::Critic::Policy::InputOutput::ProhibitInteractiveTest

I am using `-t STDERR` and am advised to use IO::Interactive instead of just the -t operator. Reading the README.md of this project, I cannot figure out why I should rather add another dependency to my project instead of just writing `-t STDERR`. I think it would be useful, if the README.md would expand on that.

Thanks!

**Comment by briandfoy** [comment]
Noted, but I don't have time for it just yet.

**Comment by briandfoy** [comment]
If you care about a particular filehandle, like `STDERR`, testing that might be adequate. But, that only means anything for that filehandle. You don't know about any other filehandle.

As for me, I don't put too much stock in the Perl::Critic tests. It's not that `-t` has a problem, but that it might not be answering the question you actually have. That policy mentions `STDIN`, but that's not the point of the policy. On page 218 of *Perl Best Practices*, it talks about ARGV, not STDIN. In fact, the actual code uses `-t STDIN`.

Here's what Damian wrote in _Perl Best Practices_:

> *ARGV won’t be opened until you read from it, and you can’t read from it until you know whether to prompt; and to know whether to prompt, you have to check where *ARGV was opened to, but *ARGV won’t be opened until you read from it.
> Several other magical properties of *ARGV can also prevent simple –t tests on the filehandle from providing the correct answer, even if the input stream is already open.

Regardless, I've provided a short explanation in the docs. See 685c469. This will be part of the next release.

**Comment by briandfoy** [comment]
I've made an issue for that policy: https://github.com/Perl-Critic/Perl-Critic/issues/938
